Uplift fix (#2962)
### Problem description
- updated `clang-format` version to `18.1.7`
Build was crashing with:
```
/__w/tt-forge-fe/tt-forge-fe/third_party/tt-mlir/third_party/tt-metal/src/tt-metal/.clang-format:77:1: error: unknown key 'InsertBraces'
InsertBraces: true
^~~~~~~~~~~~
Error reading /__w/tt-forge-fe/tt-forge-fe/third_party/tt-mlir/third_party/tt-metal/src/tt-metal/.clang-format: Invalid argument
/__w/tt-forge-fe/tt-forge-fe/third_party/tt-mlir/third_party/tt-metal/src/tt-metal/.clang-format:77:1: error: unknown key 'InsertBraces'
InsertBraces: true
```
This has happend because
[metal](https://github.com/tenstorrent/tt-metal/blob/b6d7c1c2eba6b88940c6c45ed52521e84e4407b6/.clang-format#L77)
uses `InsertBraces` from newer clang-format version (supported from 15
foward), I decided on `18.1.7` because thats the version `pre-commit`
uses
- update `unimport` `pre-commit` rev to `1.3.0` to fix missing tag
checkout
Pre-commit was failing during hook environment initialization for
`hakancelikdev/unimport` with:
```
error: pathspec '1.2.1' did not match any file(s) known to git
```
- added `target-dylib=true` to MLIR config, when output is type
`SharedObject`
This is done becuase `ttir-to-emitc-so-pipeline` was deprecated, and
instead we would want to use `ttir-to-emitc-pipeline` just with the
option `target-dylib=true`. This option is used to tell MLIR to run
`tuplify` "pass", where instead of having multiple inputs in a list
together with device, it would just put all inputs inside one vector, so
that we `<device, vec<inputs>>` instead of `<device, input1, input2
...>`. This is needed for `emitC` feature to be supported.