Remove deprecated numpy dtypes from nbeats model scripts (#2274)
### Summary

- Fixes https://github.com/tenstorrent/tt-forge-fe/issues/2275
- Remove deprecated numpy dtypes from nbeats model scripts to avoid
below error

```
E           AttributeError: module 'numpy' has no attribute 'float'.
E           `np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
E           The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
E               https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?
```

### Logs


[Nbeats_after_fix.log](https://github.com/user-attachments/files/20721015/jun13_nbeats_3.log)