Fix yolox package installation ci issue (#3009)
Fixes https://github.com/tenstorrent/tt-forge-fe/issues/3007

#### **Issue Summary**
In the [nightly
pipeline](https://github.com/tenstorrent/tt-forge-fe/actions/runs/18854341154/job/53831605920#step:14:86),
the **test collection step failed** while installing `yolox==0.3.0`
using `subprocess`.
##### Test Collection Failure:
```
AssertionError: torch is required for pre-compiling ops, please install it first.
```
This occurred even though `torch` was already installed. The issue
appeared **only when installing YOLOX through `subprocess`**, because
the `pip` installation inside the subprocess used an **isolated build
environment** by default.
In this isolated environment, preinstalled dependencies like `torch`
were not accessible — causing YOLOX’s setup script to fail when trying
to import `torch` for pre-compiling ops.

#### **Root Cause**
- `pip` uses *build isolation* by default), creating a temporary
environment without access to already installed site-packages.
- YOLOX’s `setup.py` attempts to import `torch` during build time. Since
the isolated environment doesn’t have `torch`, the build failed which
leads to test collection failures.

#### **Fix Implemented**
Disabled build isolation and improved subprocess reliability.

**Changes made:**
1. Added `--no-build-isolation` to ensure YOLOX can access the existing
`torch` installation from the main environment.
2. Replaced `"pip"` call with `[sys.executable, "-m", "pip"]` to ensure
the correct Python interpreter is used.
3. Added `check=True` to raise an exception if the subprocess command
fails, improving error visibility.


#### Note:

Verified the fix in nightly pipeline -
https://github.com/tenstorrent/tt-forge-fe/actions/runs/18902879090/job/53956216370