Fix tt-forge-fe model Migration related regressions (#2702)
### Ticket

- Fixes https://github.com/tenstorrent/tt-forge-fe/issues/2697
- Fixes https://github.com/tenstorrent/tt-forge-fe/issues/2695

### Problem description

- Xfail markers from below test cases were mistakenly removed in this
[PR](https://github.com/tenstorrent/tt-forge-fe/pull/2657)

```
forge/test/models/pytorch/vision/googlenet/test_googlenet.py::test_googlenet_pytorch[googlenet]
forge/test/models/pytorch/vision/ghostnet/test_ghostnet.py::test_ghostnet_timm[ghostnetv2_100.in1k]
forge/test/models/pytorch/vision/mlp_mixer/test_mlp_mixer.py::test_mlp_mixer_timm_pytorch[mixer_l16_224_in21k]
forge/test/models/pytorch/vision/mlp_mixer/test_mlp_mixer.py::test_mlp_mixer_timm_pytorch[mixer_b16_224_in21k]
forge/test/models/pytorch/vision/mlp_mixer/test_mlp_mixer.py::test_mlp_mixer_timm_pytorch[mixer_b16_224]
forge/test/models/pytorch/vision/mlp_mixer/test_mlp_mixer.py::test_mlp_mixer_timm_pytorch[mixer_b16_224_miil_in21k]
forge/test/models/pytorch/vision/mlp_mixer/test_mlp_mixer.py::test_mlp_mixer_timm_pytorch[mixer_b16_224.goog_in21k]
forge/test/models/pytorch/vision/mlp_mixer/test_mlp_mixer.py::test_mlp_mixer_timm_pytorch[mixer_l16_224]
```

- This [PR](https://github.com/tenstorrent/tt-forge-models/pull/52)
missed to add optional dtype conversion for input in deit leads to below
regression

```
RuntimeError: TT_ASSERT @ /proj_sw/user_dev/kkannan/jul29_bgd25/tt-forge-fe/forge/csrc/passes/dataformat.cpp:98: node->output_df() == default_df_override || node_is_int
E       info:
E       Non integer Input activations should have output_df same as dataformat override which is: Float16_b, but node output_df is: Float32
```

### What's changed
Addressed the issue by tracking
[these](https://github.com/tenstorrent/tt-forge-models/pull/64) changes
and adding xfail markers along with issue links.

### Checklist
- [x ] New/Existing tests provide coverage for changes

### Logs

-
[jul31_deit_before_fix.log](https://github.com/user-attachments/files/21524974/jul31_deit_bf.log)
-
[jul31_deit_after_fix.log](https://github.com/user-attachments/files/21524973/jul31_deit_af.log)