Fix pytorch densenet, vgg, vovnet and yolo models (#2339)
Issues Fixed:

1. `RuntimeError: TT_ASSERT @
/proj_sw/user_dev/pchandrasekaran/Forge/tt-forge-fe/forge/csrc/passes/dataformat.cpp:312:
node->output_df() == default_df_override || node_is_int Non integer
Input activations should have output_df same as dataformat override
which is: Float16_b, but node output_df is: Float32`

The below models tests contains conv ops but we have only passed
compiler config with default_df_overide to compile function without
converting models and inputs to bfloat16 which leads to above issues so
converted the model and inputs to bfloat16

```
forge/test/models/pytorch/vision/yolo/test_yolo_v3.py::test_yolo_v3
forge/test/models/pytorch/vision/yolo/test_yolo_v4.py::test_yolo_v4
forge/test/models/pytorch/vision/unet/test_vgg19_unet.py::test_vgg19_unet
```

2. `AttributeError: 'tuple' object has no attribute 'value'`
Groups and priority are passed as tuple to record_model_properties which
leads to above issues so fixed the recording in below models tests


```
forge/test/models/pytorch/vision/vovnet/test_vovnet.py::test_vovnet_timm_pytorch[ese_vovnet19b_dw.ra_in1k] forge/test/models/pytorch/vision/vovnet/test_vovnet.py::test_vovnet_timm_pytorch[ese_vovnet19b_dw]
forge/test/models/pytorch/vision/vovnet/test_vovnet.py::test_vovnet_timm_pytorch[ese_vovnet39b]
forge/test/models/pytorch/vision/vovnet/test_vovnet.py::test_vovnet_timm_pytorch[ese_vovnet99b]
```

3. `_pickle.UnpicklingError: Weights only load failed. This file can
still be loaded, to do so you have two options, [1mdo those steps only
if you trust the source of the checkpoint(1) In PyTorch 2.6, we changed
the default value of the `weights_only` argument in `torch.load` from
`False` to `True`. Re-running `torch.load` with `weights_only` set to
`False` will likely succeed, but it can result in arbitrary code
execution. Do it only if you got the file from a trusted source. (2)
Alternatively, to load with `weights_only=True` please check the
recommended steps in the following error message.`


The above error was through while loading densenet model(i.e
densenet121-res224-all ) weights in this
[line](https://github.com/mlmed/torchxrayvision/blob/11c53a046ea7335cf3b132d61c22af81290748d5/torchxrayvision/models.py#L210)
due to recent torch update. The densenet model class doesn't have
argument to set weight_only argument to False so using the flag
[TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD](https://docs.pytorch.org/docs/stable/miscellaneous_environment_variables.html#:~:text=TORCH_FORCE_NO_WEIGHTS_ONLY_LOAD)
to set weight_only to False

`

forge/test/models/pytorch/vision/densenet/test_densenet.py::test_densenet_121_pytorch[densenet121_hf_xray]
`