Fix runtime tensor type error by disabling return_dict (#2059)
### Problem description

```
RuntimeError: Unknown type of tensor: <class 'transformers.modeling_outputs.ImageClassifierOutput'>
RuntimeError: Unknown type of tensor: <class 'transformers.modeling_outputs.ImageClassifierOutputWithNoAttention'>
AttributeError: 'ForgePropertyHandler' object has no attribute 'record_model_propertiese'
```

### What's changed

- Runtime error was resolved by setting return_dict=False. This forces
the model to return outputs as tuples instead of dict & post processing
steps are added as tests passing e2e.
- Typo in record_model_properties is corrected

Note: `facebook/deit-base-distilled-patch16-224,
facebook/deit-small-patch16-224,facebook/deit-tiny-patch16-224 `all this
variants are passing e2e. but only base variant
(facebook/deit-base-distilled-patch16-224) is added to push marker.

### Logs


[may16_deit_before_fix.log](https://github.com/user-attachments/files/20256794/may16_deit_bf.log)

[may16_deit_after_fix.log](https://github.com/user-attachments/files/20256793/may16_deit_af_1.log)

[may16_regnet_classi_before_fix.log](https://github.com/user-attachments/files/20256796/may16_regnet_classi_bf.log)

[may16_regnet_classi_after_fix.log](https://github.com/user-attachments/files/20256795/may16_regnet_classi_af_1.log)