[Bug Fix] Fix decompose_nd_reshape_split pass (#2413)
### Problem description
Tests:
-
`forge/test/models/pytorch/text/bloom/test_bloom.py::test_bloom[bigscience/bloom-1b1]`
-
`forge/test/models/pytorch/multimodal/stable_diffusion/test_stable_diffusion_xl.py::test_stable_diffusion_generation[stable-diffusion-xl-base-1.0]`
were failing due to the error:
```
RuntimeError: TT_ASSERT @ /__w/tt-forge-fe/tt-forge-fe/forge/csrc/graph_lib/shape.cpp:135: (i >= 0) && (i < (int)dims_.size())
```
which was caused by the wrong assumptions in the
`decompose_nd_reshape_split` pass.
### What's changed
- Fixed the pass and added additional constraints to it
- Added comprehensive pass description with clear before/after examples
- Added unit tests