Fix: missing 1 required positional argument: 'self' in vgg19_unet ModelLoader (#2730)
### Issue Ticket
https://github.com/tenstorrent/tt-forge-fe/issues/2759

### Description
This PR Includes the fix for the issue `TypeError:
ModelLoader.load_model() missing 1 required positional argument: 'self'`

### What's changed
The test script of the vgg19_unet has been modified

### Checklist
- [x] New/Existing tests provide coverage for changes

### Model Log
Before Fix

[vgg19_unet_before.log](https://github.com/user-attachments/files/21660869/vgg19_unet.log)
After Fix

[vgg19_unet_after.log](https://github.com/user-attachments/files/21583343/vgg19_unet.log)