Fix deepseek and oft model and add skip_model_analysis markers for models blocks/parts tests (#2882)
The PR will fix deepseek and oft models issues and added
skip_model_analysis markers for models blocks tests.


1. `padded_inputs, seq_len = loader.load_inputs() ValueError: not enough
values to unpack (expected 2, got 1)`

The deepseek model was failing with above issues because the load_inputs
only returns the padded inputs so fixed it by accepting padded_inputs
and no need to pass seq_len to decode_output method because the
decode_output method will take seq_len from the ModelLoader class data
member.

Failed cases:


`forge/test/models/pytorch/multimodal/deepseek_coder/test_deepseek_coder.py::test_deepseek_inference_no_cache[1_3b_instruct]`

2. `TypeError: ModelLoader.load_model() missing 1 required positional
argument: 'self'`

The oft model was failing with above issues because the ModelLoader was
initialized and called the load_model method.

Failed cases:

`forge/test/models/pytorch/vision/oft/test_oft.py::test_oft`