Upgrades jax to 0.6.1 (#2346)
### Ticket
[Link to Github
Issue](https://github.com/tenstorrent/tt-forge-fe/issues/2327)

### Problem description
To address below issue 
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tt-forge-fe 0.1.0.dev20250617 requires jax==0.4.30, but you have jax 0.6.1 which is incompatible.

```

---------

Co-authored-by: Sai Arthi Raguram <ctr-sraguram@ext.tenstorrent.com>