Fix blip, clip and chineseclip paddlepaddle models (#2478)
In PaddlePaddle’s framework, BLIP, CLIP, and ChineseCLIP model tests
were failing during the Paddle‑to‑Relay conversion with:
`
TVMError: relay.concatenate requires all tensors to have the same shape
on non‑concatenating axes
`
The root cause was that the `broadcast_to` operator was emitting output
shapes containing -1. Fixed this in TVM by passing a fully‑specified
broadcast shape to the size argument and added sanity tests. Fixing
these issue help to generate models ops tests for paddle models which
help to cover large number of unique ops config.