Add test for deepseek_math prefill (#1201)
Deepseek math test and deepseek math prefill test is now failing with
below runtime error:
```
RuntimeError: TT_THROW @ /proj_sw/user_dev/mramanathan/bgdlab12_feb10_forge/tt-forge-fe/third_party/tt-mlir/third_party/tt-metal/src/tt-metal/tt_metal/impl/allocator/bank_manager.cpp:132: tt::exception
E       info:
E       Out of Memory: Not enough space to allocate 180355072 B DRAM buffer across 12 banks, where each bank needs to store 15032320 B
```