Fix yolov5 regression (#2072)
Fixes https://github.com/tenstorrent/tt-forge-fe/issues/2061

In the [nightly models
pipeline](https://github.com/tenstorrent/tt-forge-fe/actions/runs/15101350747/job/42468321702),
yolov5 test was failing with `YOLOv5 loading error: cannot import name
'TryExcept' from 'utils'
(/__w/tt-forge-fe/tt-forge-fe/forge/test/models/onnx/vision/mobilenetv2/utils/__init__.py)`
while loading the yolov5 model in the `yolov5_loader` function present
in `forge/test/utils.py`

The issues is caused by having multiple versions of the utils.py file in
python path and it is taking the utils package from this path
`forge/test/models/onnx/vision/mobilenetv2/utils/__init__.py`, instead
of yolov5 utils.

To resolve the issues, I have renamed the package name from `utils` to
`model_utils` in the `forge/tests/models` path based upon the fix
suggested from [official
ultralytic/yolov5](https://github.com/ultralytics/yolov5/issues/10323#issuecomment-1556071691)
issues.

Triggered the nightly pipeline to verify the fix and now all the yolov5
tests passed -
https://github.com/tenstorrent/tt-forge-fe/actions/runs/15115781083